name: tut_student_kiosk
description: TUT Student Kiosk Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.1.0
  chat_bubbles: ^1.5.0
  marquee: ^2.2.3
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.1.0
  webview_flutter: ^4.4.2
  webview_flutter_web: ^0.2.2+3
  webview_flutter_platform_interface: ^2.6.0
  url_launcher: ^6.1.14
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/
    - images/
    - images/identity_checkpoint.svg
    - images/login.svg
    - images/register.svg
    - images/forgot_pin.svg
    - images/logo_top.png
    - images/logo.png
    - images/logo_nav.png
    - images/logo_nav.webp
    - assets/dialogflow_credentials.json
    - .env
    
  fonts:
    - family: Ruda
      fonts:
        - asset: fonts/Ruda-Regular.ttf
        - asset: fonts/Ruda-Bold.ttf
          weight: 700
