name: tut_student_kiosk
description: TUT Student Kiosk Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  flutter_spinkit: ^5.2.0
  flutter_dotenv: ^5.1.0
  chat_bubbles: ^1.5.0
  marquee: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - images/
    - images/logo_top.png
    - images/logo.png
    - images/identity_checkpoint.svg
    - assets/dialogflow_credentials.json
    - .env
    
  fonts:
    - family: Ruda
      fonts:
        - asset: fonts/Ruda-Regular.ttf
        - asset: fonts/Ruda-Bold.ttf
          weight: 700
